### ISSUE TITLE
Review and update for underhanded contest results

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/smart-contract-best-practices#102]
I think there are some novel items in here that we need to incorporate, but I haven't look at all of them yet.

https://medium.com/@chriseth/lessons-learnt-from-the-underhanded-solidity-contest-8388960e09b1
https://github.com/Arachnid/uscc/tree/master/submissions-2017/
https://medium.com/@weka/announcing-the-winners-of-the-first-underhanded-solidity-coding-contest-282563a87079

**Comment by maurelian** [comment]
@shayanb I wonder if the issues items we added for this might have been a better fit for their own section, or perhaps simply being linked to. They are much more involved to describe...

**Comment by shayanb** [comment]
@maurelian What do you have in mind for "their own section"? I was thinking of having a CTF samples section to have these in there, maybe even link Steve's twitch solutions in the same page. but it might not get the point across as possible attack vectors.

**Comment by maurelian** [comment]
Yes, Something like CTF samples makes more sense, as the USCC was kind of a CTF design competition in some sense. The point is that these sneaky design patterns are very hard to distil into a single recommendation or known attack. It might even be better just to describe them very briefly and link elsewhere.
