### ISSUE TITLE
Should we keep the "Future Improvements" page?

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/smart-contract-best-practices#115]
https://consensys.github.io/smart-contract-best-practices/future_improvements/

If so it needs an update.

**Comment by maurelian** [comment]
Same question for the bibliography: https://consensys.github.io/smart-contract-best-practices/bibliography/

**Comment by devzl** [comment]
I think the future improvements part is useless.

For the bibliography, it should be kept for further reading and discovery.

**Comment by mimoo** [comment]
I think it should be kept and it should focus on formal verification of contracts.

**Comment by addojames11** [comment]
It should be kept

**Comment by maurelian** [comment]
PRs are welcome. :)
