### ISSUE TITLE
Should we lock pragma?

### ISSUE THREAD

**Issue by nemild** [ConsenSys/smart-contract-best-practices#125]
This guide argues that [pragma be locked](https://github.com/ConsenSys/smart-contract-best-practices/blob/master/docs/recommendations.md) to a specific version.

The Ethereum Solidity guide [argues that pragmas should be allowed to move up in the patch version](https://solidity.readthedocs.io/en/develop/layout-of-source-files.html) (e.g., `^0.4.20` rather than `0.4.20`): 
> We do not fix the exact version of the compiler, so that bugfix releases are still possible.

We should probably debate this, and then make a recommendation. Are there examples in the past where either way caused an issue? If both have caused issues, may want to just highlight tradeoff. Anyone else we should consult on this?

(cc: @ethers)

**Comment by maurelian** [comment]
In my opinion, pragmas should include `^` until the time of deployment, or an audit. They should then be locked to make it clear at which version the deployed versions were compiled at. Source code pragmas should also be locked when verified on etherscan or other similar services.

**Comment by nemild** [comment]
Makes sense.

And yet another use case is a contract created primarily to be used by others. For example, the [Zeppelin contracts](https://github.com/OpenZeppelin/zeppelin-solidity/). In this case, I do think there are advantages to include the `^`, as presumably bugs may discovered since the contract was first created, and this contract "lives" on Github, not just on the blockchain.

As a next step, I think we should just list out the background behind the advice and recommend when a `^` is preferred, and when it is not. @maurelian I am happy to take a first crack, if you'd like. I'll suggest that there are times to include the `^` and times to exclude it.

**Comment by maurelian** [comment]
That does sound to me like quite a valid use case @nemild, and I would very much appreciate you taking a first crack at that!

**Comment by sohkai** [comment]
We also had a similar discussion in aragon-core (https://github.com/aragon/aragon-core/pull/160).

The two major use cases I see for including `^` are "library" contracts (like those in Zeppelin) and "interface" contracts (like ERC standards or those someone who wants to interface with your contract might want). Any critical component that's relatively complex and has been deployed should be locked.

**Comment by maurelian** [comment]
> "library" contracts (like those in Zeppelin)

On a somewhat related note, are you using EthPM to install Zeppelin? I find it unsettling when people copy and paste one or two contracts.

**Comment by sohkai** [comment]
We are not yet, but I agree, it is unsettling. Seems to be fairly widespread practice though.

**Comment by izqui** [comment]
> @maurelian On a somewhat related note, are you using EthPM to install Zeppelin?

We treat every piece of code that gets imported in our repos as our own, in terms of code review and auditing. I'm quite concerned about code that we import changing under us without noticing for any reason (not locking ethpm versions correctly, vulnerability in tooling, etc).  

We also only use a couple of silly contracts, no need for us to have the full Zeppelin dependency.

**Comment by maurelian** [comment]
OK, is a reasonable summary here: 

* If the contract is intended to be used by others (ie. a framework, or EPM package), it makes sense to include `^`. 
* Otherwise, pin it. 

Or did I miss another case where it should be floated?

**Comment by maurelian** [comment]
closed in https://github.com/ConsenSys/smart-contract-best-practices/commit/f15ca95557aad8c1ebe59c5feea4a91e3d729948
