### ISSUE TITLE
Section Pitfalls in Race Condition Solutions

### ISSUE THREAD

**Issue by djeang** [ConsenSys/smart-contract-best-practices#126]
Hi,

I don't understand : _// At this point, the caller will be able to execute getFirstWithdrawalBonus again_

According Solidity official documentation about internal function call 

> These function calls are translated into simple jumps inside the EVM

So I can't figure how a caller can take control of the flow here. Can you describe how  ?

```
// INSECURE
mapping (address => uint) private userBalances;
mapping (address => bool) private claimedBonus;
mapping (address => uint) private rewardsForA;

function withdraw(address recipient) public {
    uint amountToWithdraw = userBalances[recipient];
    rewardsForA[recipient] = 0;
    require(recipient.call.value(amountToWithdraw)());
}

function getFirstWithdrawalBonus(address recipient) public {
    require(!claimedBonus[recipient]); // Each recipient should only be able to claim the bonus once

    rewardsForA[recipient] += 100;
    withdraw(recipient); // At this point, the caller will be able to execute getFirstWithdrawalBonus again.
    claimedBonus[recipient] = true;
}
```

**Comment by djeang** [comment]
Sorry, 

I got it : as `withdraw ` in turn calls  an external function, caller can take control.

**Comment by maurelian** [comment]
No problem. In the future, feel free to ask in the gitter chat:

https://gitter.im/ConsenSys/smart-contract-best-practices
