### ISSUE TITLE
Document the short address attack mitigation failure

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/smart-contract-best-practices#128]
https://blog.coinfabrik.com/smart-contract-short-address-attack-mitigation-failure/

**Comment by maurelian** [comment]
Upon further review, a very short summary is: 

> Be aware that solidity's `address.call(data)` will right pad the data to 32*n bytes. https://github.com/ethereum/solidity/issues/2884

**Comment by mimoo** [comment]
As far as I see, the page is not documenting short address attacks in the first place
