### ISSUE TITLE
Improve upgradeability section

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/smart-contract-best-practices#164]
This [post](https://blog.trailofbits.com/2018/09/05/contract-upgrade-anti-patterns/) from our friends at Trail of Bits made reference to some outdated content in our best practices. 

It definitely needs to be revisited, and in the shorter term, possibly removed or wrapped in a big fat caveat.

**Comment by shayanb** [comment]
No links from the mentioned post to Best practices exist at this time. 

Related section: https://consensys.github.io/smart-contract-best-practices/software_engineering/

**Comment by maurelian** [comment]
They took it down.... but we should definitely discuss that section's value.

**Comment by KadenZipfel** [comment]
Here are some great resources on the topic:

https://blog.openzeppelin.com/proxy-patterns/
https://blog.openzeppelin.com/towards-frictionless-upgradeability/
https://blog.openzeppelin.com/upgradeability-using-unstructured-storage/

**Comment by maurelian** [comment]
I think the right way to handle this is: 
1. Write a paragraph about the risks and arugments against upgradability
2. Link to other resources such as those from Zepp and ToB above.

**Comment by fodisi** [comment]
Hi,
I just submitted PR #244 to address this issue. I'm fully open to rework my proposal based on the community feedback.

Thank you.

**Comment by shayanb** [comment]
merged in https://github.com/ConsenSys/smart-contract-best-practices/issues/164
