### ISSUE TITLE
How about providing PDF document?

### ISSUE THREAD

**Issue by jtjisgod** [ConsenSys/smart-contract-best-practices#168]
How about providing PDF document?

I like reading printed document. but, This document site is not providing pdf document.
So, I request you that upload pdf version document.

( I'm already converted this document to pdf  using with http://www.markdowntopdf.com/ )

**Comment by jtjisgod** [comment]
[document.pdf](https://github.com/ConsenSys/smart-contract-best-practices/files/2404812/document.pdf)

This is pdf of this document.

**Comment by maurelian** [comment]
Thank you for your suggestion.

However, this site is ever evolving, and so any PDF will be outdated. I think it's best that readers find their own solution for printing.
