### ISSUE TITLE
Guidance related to the safe use of the `int` type

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/smart-contract-best-practices#171]
Thanks to @dappsec for pointing this out to me. These words are mostly his:

Here's a bit of a puzzle demonstrating the problem:

<img width="619" alt="screen shot 2018-09-30 at 4 51 51 pm" src="https://user-images.githubusercontent.com/23033765/47238390-0b2cf280-d3b0-11e8-9acc-feb128e609c6.png">

This is one of two 256-digit signed values where the unary negation operator returns the same value.
`-57,896,044,618,658,097,711,785,492,504,343,953,926,634,992,332,820,282,019,728,792,003,956,564,819,968`
or
`0x8000000000000000000000000000000000000000000000000000000000000000`

In this case, the number remains negative after unary negation.
(Blame two-complement arithmetic.)
The other value that does this is zero.

If it’s an `int8`, then the weird value is `0x80` or `-128`.

Same issue exists in C/C++ and many other languages.

**Comment by dappsec** [comment]
Meant to write "Blame two's complement arithmetic" in my original message.

**Comment by NickErrant** [comment]
Related issue (actual overflow though) exists with multiplication and division of signed ints in special case:
https://github.com/RequestNetwork/requestNetwork/issues/43
https://github.com/JoinColony/colonyNetwork/issues/417
