### ISSUE TITLE
Block Stuffing documentation

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/smart-contract-best-practices#182]
See: https://osolmaz.com/2018/10/18/anatomy-block-stuffing/

This is a form of DOS, and somewhat related to https://consensys.github.io/smart-contract-best-practices/recommendations/#in-2-party-or-n-party-contracts-beware-of-the-possibility-that-some-participants-may-drop-offline-and-not-return.

Basically, anytime you can gain or grief by preventing an action before a specific time, this issue exists.

**Comment by aj07** [comment]
In the link https://osolmaz.com/2018/10/18/anatomy-block-stuffing/  , he described in very good way that how hacker hacked Fomo3D. But, there is no description on how it can be prevented. Only thing mentioned is that in PoS this would be very complex. @maurelian what should we include about it.
