### ISSUE TITLE
Add: Prefer external over public for function visibility

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/smart-contract-best-practices#187]
Add to Solidity specific recommendations:

Saves gas (at least unoptimized), but especially it provide certainty that the function has a single entry point 
via an call from another account.

**Comment by shayanb** [comment]
Added [0e56e46de8152d59a1b766a09e7e6e077ddb1acc](https://github.com/ConsenSys/smart-contract-best-practices/blob/0e56e46de8152d59a1b766a09e7e6e077ddb1acc/docs/recommendations.md#explicitly-mark-visibility-in-functions-and-state-variables)
