### ISSUE TITLE
Change 'race condition' terminology 

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/smart-contract-best-practices#188]
I don't think reentrancy is properly classified as a race condition, change my mind.

**Comment by cwellsx** [comment]
IMO a "race condition" is necessarily an artefact of multi-threaded code ... and may or may not happen (isn't deterministic) depending on timing, time-slicing, etc. Locks (e.g. mutexes) may be used to avoid race conditions ... and locks often don't support reentrancy (e.g. they deadlock).

So I think that the reentrancy between contracts which you describe isn't what I'd call a race condition.

Nevertheless https://consensys.github.io/smart-contract-best-practices/recommendations/ currently contains a hyperlink to "Race Conditions" (https://consensys.github.io/smart-contract-best-practices/known_attacks#race-conditions) which (the target) doesn't exist.
