### ISSUE TITLE
is pragma lock really relevant?

### ISSUE THREAD

**Issue by mimoo** [ConsenSys/smart-contract-best-practices#192]
cf https://consensys.github.io/smart-contract-best-practices/recommendations/#lock-pragmas-to-specific-compiler-version

> Contracts should be deployed with the same compiler version and flags that they have been tested the most with. Locking the pragma helps ensure that contracts do not accidentally get deployed using, for example, the latest compiler which may have higher risks of undiscovered bugs. Contracts may also be deployed by others and the pragma indicates the compiler version intended by the original authors.

According to [Solidity's documentation](https://solidity.readthedocs.io/en/v0.4.24/layout-of-source-files.html#version-pragma) this prevent compilation with updates that bring breaking changes. I'm assuming that it might also prevent uses of beta versions (although I'd like a confirmation on that). In that sense, it makes more sense to use `^` in order to have automatic bug fixes rather than not using `^`.

**Comment by mimoo** [comment]
Actually I just confirmed that 

```
pragma solidity ^0.4.25;
```

will compile fine with `0.4.26-nightly.2018.9.25`. So that's bad, probably a semantic version bug? (I don't know much about semver). Probably this is worth mentioning in the section.

**Comment by maurelian** [comment]
For context, this was discussed previously in #125. To me, the most important benefit of pragma locking is to explicitly communicate to future readers which compiler version was actually used. 

It's a good point that nightlies should be considered as beta and not allowed by `^`. I'll add a note. 

ps. here's an awesome semver resource: https://semver.npmjs.com/, though

**Comment by mimoo** [comment]
I've only confirmed this with remix, which seems to use your npm library
