### ISSUE TITLE
Add vyper translations alongside solidity

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/smart-contract-best-practices#193]
Let's make these docs multilingual!

## Spec

1. Move all the solidity code samples appearing in the docs into a new dir, with a descriptive title. 
2. Using the [snippets feature of PyMDown](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#overview), insert the solidity code samples.
3. Using the [super-fences feature](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#overview), add a vyper tab alongside each solidity example.
4. Translate the solidity code samples into vyper equivalents in a directory adjacent to the solidity samples.
5. Similar to step 2, insert the vyper samples. 

For now, it's OK if the Solidity samples don't compile. The Vyper samples should.

Our doc system uses [MKDocs](https://www.mkdocs.org/), with the [Material Theme](https://squidfunk.github.io/mkdocs-material/extensions/pymdown/), which includes [PyMDown](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#overview).

**Comment by maurelian** [comment]
Here's a better superfences reference:
https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#tabbed-fences

**Comment by shayanb** [comment]
@carlfarterson we closed this issue a while ago. just assigned it to you in case it's still something you want to do.
