### ISSUE TITLE
Add Colony Bug Bounty to List of Smart Contract Bug Bounty Programs

### ISSUE THREAD

**Issue by jacklaing** [ConsenSys/smart-contract-best-practices#204]
Colony: [Launched](https://blog.colony.io/announcing-the-colony-network-bug-bounty-f44cabaca9a3/) November 2018, max payout $20k

You can also read [here](https://blog.colony.io/for-whom-the-delegate-calls/) for a primer on the colonyNetwork contracts.

**Comment by shayanb** [comment]
Added in a37d24144013d0b34487d505a188c8f2dffcec2e
