### ISSUE TITLE
Mistake calling `underflow`

### ISSUE THREAD

**Issue by nakajo2011** [ConsenSys/smart-contract-best-practices#219]
The title `Integer Overflow and Underflow` is mistake. I think it is (negative) overflow.

**Comment by cleanunicorn** [comment]
I don't think it's actually a mistake. "Underflow" is used in a lot of places and the definition matches what we want to express.

Wiki:
> The term arithmetic underflow (or "floating point underflow", or just "underflow") is a condition in a computer program where the result of a calculation is a number of smaller absolute value than the computer can actually represent in memory on its CPU.

Google definition:
> the generation of a number that is too small to be represented in the device meant to store it.
