### ISSUE TITLE
Accepted token standards

### ISSUE THREAD

**Issue by KadenZipfel** [ConsenSys/smart-contract-best-practices#234]
Currently listed in our [accepted token standards](https://consensys.github.io/smart-contract-best-practices/tokens/#comply-with-the-latest-standard), we have EIP20 & EIP721. Are we ready to add any other token standards to this list?

**Comment by shayanb** [comment]
Ideally I like to see a better taxanomy of tokens and the common issues of each (maybe similar to  this: [SecurityToken section](https://github.com/ConsenSys/polymath-audit-report-2019-04#design).
Or maybe also use a taxanomy of diffrentiating the tokens based on their nature (e.g. https://medium.com/cryptolawreview/token-taxonomy-frameworks-de968bf2605c) 

This is just a brainstorming comment, open to suggestions

**Comment by KadenZipfel** [comment]
I very much like the idea of having a taxonomy of tokens, and I think the second link does a good job at classifying them. 

However, I think the difficulty with adding to our accepted token standards is determining whether they're suitable from a security standpoint. I think that it would be good to start by possibly adding to [this list](https://consensys.github.io/smart-contract-best-practices/tokens/#comply-with-the-latest-standard), with any standards that we deem acceptable from a security standpoint. Then at the bottom of this page have a classification of tokens along with some kind of caveat that they haven't been tested as much as our accepted standards.

**Comment by maurelian** [comment]
Addressed this in a3f916f295e7a4d0055e3264e30f1baf2084fe65
