### ISSUE TITLE
Update to be made after Istanbul

### ISSUE THREAD

**Issue by KadenZipfel** [ConsenSys/smart-contract-best-practices#235]
[This section](https://consensys.github.io/smart-contract-best-practices/recommendations/#avoid-transfer-and-send) will have to be updated after Istanbul.

**Comment by maurelian** [comment]
Would welcome a PR for this.

**Comment by maurelian** [comment]
Bump :)

**Comment by KadenZipfel** [comment]
https://github.com/ConsenSys/smart-contract-best-practices/pull/242
