### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by MeherRoy** [ConsenSys/smart-contract-best-practices#50]
In the code for refunding multiple addresses by iterating over a loop, shouldn't Line 5 in the code be Payee[] payees; instead of Payee payees[]?

struct Payee {
    address addr;
    uint256 value;
}
Payee payees[];
uint256 nextPayeeIndex;

**Comment by simondlr** [comment]
Yes. That's a typo! Will fix soon. Thanks @MeherRoy!
