### ISSUE TITLE
Explicit parentheses for compound expressions

### ISSUE THREAD

**Issue by ethers** [ConsenSys/smart-contract-best-practices#51]
Should we add this?

Rule 18
In compound expressions with multiple sub-expressions the intended
order of evaluation shall be made explicit with parentheses. [cf. MISRAC:2004
Rule 12.2] 

http://lars-lab.jpl.nasa.gov/JPL_Coding_Standard_C.pdf

(we could add the obvious caveat that "However, do not add too many parentheses so as to clutter the code and make it unreadable." per MISRAC:2004 Rule 12.1)

**Comment by maurelian** [comment]
This would belong in a style guide section, which we do not have.
