### ISSUE TITLE
Add tip to be cautious about using `send(value)` when `value` can be 0.

### ISSUE THREAD

**Issue by CJentzsch** [ConsenSys/smart-contract-best-practices#59]
When `send` is used, it will only give a gas stipend for non-zero value transfer (Yellow Paper Appendix H description of "CALL" (last line) ). If the recipient is a normal account (without code), it will work and return 1. If it is a smart contract with code to be executed, such as the multisig, it will fail with an out-of-gas exception and return 0. (since it needs gas to execute this line: https://github.com/ethereum/dapp-bin/blob/d9e8f0de17db153749920c01ea77e910a4a92b45/wallet/wallet.sol#L336)

An example for this failure can be found here: https://github.com/BitySA/whetcwithdraw/blob/086170f38eef1762726c4109a3ed713d79b87c26/whetcwithdraw.sol#L116 ( White Hat Hacker Withdraw Contract). When someone will donate nothing it throws an exception since it tries to call the standard multisig.

**Comment by simondlr** [comment]
Thanks @CJentzsch.

So, to confirm: sending with 0 does NOT provide any gas stipend at all? So it will just throw if the fallback has ANY code in it? Would it still throw if there's no fallback function?

**Comment by CJentzsch** [comment]
Right, it does not send any gas. So no code which costs any gas can be executed. 
So the only code which can be executed is the one with free opcodes (see yellow paper section H.1) which are: `{STOP, SUICIDE, RETURN}` (but there isn't even gas to PUSH the address or the bytes used as input parameter in SUICIDE or RETURN, so the input parameter would be `0x00...00`)
I do not know the exact implementation of the solidity compiler (@chriseth?), but even if the fallback function would be empty, I guess the first check in the code is whether there is some data in the call, and only if empty it calls the fallback function. Even this check would cost gas and fail.

**Comment by simondlr** [comment]
Either way, it seems as with the whitehat DAO contract it could be an issue if the contract does not expect that it could send 0 (expecting it succeed).

+1

**Comment by chriseth** [comment]
send never provides gas, that's how it is designed. I created an issue to discuss whether the compiler should handle the special case of `send(0)`: https://github.com/ethereum/solidity/issues/977

I would make a general recommendation that you should be prepared that send can always fail for whatever reason even if you know the target contract.

**Comment by ethers** [comment]
`send(0)` now gets the stipend https://github.com/ethereum/solidity/pull/1008 so does not have its own specific reason that it could fail.  Seems this can be closed?
