### ISSUE TITLE
Sol 0.4.x: new payable modifier only affects external calls

### ISSUE THREAD

**Issue by simondlr** [ConsenSys/smart-contract-best-practices#67]
"Something that might not be obvious: The payable modifier only applies to calls from external contracts. If I call a non payable function in the payable function in the same contract, the non-payable function won't fail, though msg.value is still set."

from @Georgi87. Thanks for this.

**Comment by shayanb** [comment]
Added https://github.com/shayanb/smart-contract-best-practices/commit/0cd18f8f67dd40b10237d3984f35b2b41f77c027
