### ISSUE TITLE
May need 'payable'?

### ISSUE THREAD

**Issue by readytopark** [ConsenSys/smart-contract-best-practices#69]
In "Keep fallback functions simple" section,

`function deposit() external { balances[msg.sender] += msg.value; }`

Does't this function need "payable" modifier to work properly?

**Comment by simondlr** [comment]
That is correct. Thanks @readytopark.

**Comment by ethers** [comment]
Thanks you @readytopark!  Feel free to submit a pull request if you see payable missing in other areas, or if you have other improvements :)
