### ISSUE TITLE
I think the "Pitfalls in Race Condition Solutions" can not work the way you expect

### ISSUE THREAD

**Issue by maiffany** [ConsenSys/smart-contract-best-practices#71]
You've mentioned in your wiki that to solve race condition attack, one can use a lock variable. I quote your code here. And I don't think a lock variable can solve parallel invoking. As you are setting lockBalances to true, I can still go into the withdraw function and thus withdraw the balance again.

```
function deposit() public returns (bool) {
    if (!lockBalances) {
        lockBalances = true;
        balances[msg.sender] += msg.value;
        lockBalances = false;
        return true;
    }
    throw;
}

function withdraw(uint amount) public returns (bool) {
    if (!lockBalances && amount > 0 && balances[msg.sender] >= amount) {
        lockBalances = true;

        if (msg.sender.call(amount)()) { // Normally insecure, but the mutex saves it
          balances[msg.sender] -= amount;
        }

        lockBalances = false;
        return true;
    }

    throw;
}
```

**Comment by simondlr** [comment]
Hey!

> I can still go into the withdraw function and thus withdraw the balance again.

How? lockBalances is set to True *before* the external call is done. Doing a re-entry here, will cause a throw.

**Comment by maiffany** [comment]
Before you set lockBalances  to True, one can entry the func and withdraw the balance. This way can not solve parallel invoking.

**Comment by simondlr** [comment]
> Before you set lockBalances to True, one can entry the func and withdraw the balance.

I don't understand. How is this possible? In withdraw(), there's no possible way to re-enter *before* lockBalances is set. If you are thinking about 2 *different* transactions being used, then that is not possible at all. Execution is not parallel in Ethereum. It is in serial. So, the lock will re-open itself after each transaction.

**Comment by maiffany** [comment]
Yes, I am thinking about 2 different txs being used. If there is no parallel in Ethereum, how could re-enter happen? Because all the txs happen in line, and the invoke of the contract is triggered by transaction, so at one time the function can only be execute once. Seemed like there is no way to withdraw the balance twice.

**Comment by simondlr** [comment]
When you call a new function, the function is not completed yet. It first completes the sub-call before continuing. The sub-call can re-call the function you are in. That's how you re-enter.

The section on reentrancy explains it quite well. https://github.com/ConsenSys/smart-contract-best-practices#reentrancy.

**Comment by maiffany** [comment]
Got it! I misunderstood the meaning of reentrancy. I thought it means invoked by another transaction again.
Thank you so much for your time and guide!

**Comment by simondlr** [comment]
No worries! Might be useful to add a graphic/drawing in there to describe it. :)
