### ISSUE TITLE
Add in new safety features from 0.4.10

### ISSUE THREAD

**Issue by simondlr** [ConsenSys/smart-contract-best-practices#75]
https://www.reddit.com/r/ethereum/comments/5zkuwj/solidity_0410_released/

Included things like transfer() which is equivalent to if(!send()) { throw; }

**Comment by maurelian** [comment]
Added in #77

**Comment by maurelian** [comment]
@simondlr can you close this, and give me the permission to do so in the future. :)

**Comment by simondlr** [comment]
Done. :)
