### ISSUE TITLE
Please add a warning about using Constant State Variables

### ISSUE THREAD

**Issue by bokkypoobah** [ConsenSys/smart-contract-best-practices#76]
Details documented in [TIB (Today I Burnt) 0.01 ETH Using Constant State Variables In A Solidity Contract](https://www.reddit.com/r/ethdev/comments/60xklu/tib_today_i_burnt_001_eth_using_constant_state/).

Using a constant state variables produces unexpected results, for example:

    uint256 public constant PRESALE_START_DATE = now;
    uint256 public constant PRESALE_END_DATE = PRESALE_START_DATE + 15 minutes;
    uint256 public constant OWNER_CLAWBACK_DATE = PRESALE_START_DATE + 20 minutes;

The variables:

* PRESALE_START_DATE will ALWAYS have the current time value
* PRESALE_END_DATE will ALWAYS have a date 15 minutes in the future
* OWNER_CLAWBACK_DATE will ALWAYS have a date 20 minutes in the future

Sample contract at [0xe67907329dafd1ff826523e3f491bec8733f7376](https://etherscan.io/address/0xe67907329dafd1ff826523e3f491bec8733f7376#readContract). Refresh the page and you will see these **constant** variables update. **DO NOT SEND FUNDS TO THIS CONTRACT**

**Comment by simondlr** [comment]
Wow. Nice catch! That's unexpected behaviour.

**Comment by bokkypoobah** [comment]
Thanks.

**Comment by simondlr** [comment]
@bokkypoobah does this fix this issue? https://github.com/ethereum/solidity/pull/1729

**Comment by bokkypoobah** [comment]
Sound like it will.

**Comment by chriseth** [comment]
The fix is part of 0.4.10.

**Comment by bokkypoobah** [comment]
nice

**Comment by simondlr** [comment]
Thanks @chriseth. Closing this then. Thanks again @bokkypoobah!
