### ISSUE TITLE
Missing semicolon

### ISSUE THREAD

**Issue by AlexXiong97** [ConsenSys/smart-contract-best-practices#81]
In the "Using Registry contract to store the latest version of the contract" part, the example code has a missing semicolon:

`modifier onlyOwner() {
        if (msg.sender != owner) {
            throw;
        }
        _
    }`

there should be a semicolon at the back of `_`

And several following examples have the same issue.

**Comment by simondlr** [comment]
Thanks for picking this up @AlexXiong97!
