### ISSUE TITLE
Clarify timestamp guidance

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/smart-contract-best-practices#83]
It seems to be a bit overly prescriptive, especially given the size of the current reward, for certain use cases timestamps should be fairly safe. 

Perhaps we can quantify what values, or granularities of time are safe. 

Reference:
https://ethereum.stackexchange.com/questions/413/can-a-contract-safely-rely-on-block-timestamp/432#432

**Comment by maurelian** [comment]
@djphillyg you can take this on when you're done your research. :)

**Comment by mimoo** [comment]
> Also still asking for a reference on the 12 minute rule.

It lacks a reference on that. I've looked at geth's code and it checks if it's older than the previous block + not more than 15 seconds in the future.
