### ISSUE TITLE
Recommendations for preventing address switching attacks

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/smart-contract-best-practices#85]
The example I'm thinking of is CoinDash. 

Possible options include: 
* using the ENS to demonstrate ownership
* publishing addresses well in advance.
* hosting the site on IPFS

**Comment by simondlr** [comment]
Out of curiosity, do we know how their site was hacked and the address replaced?

**Comment by maurelian** [comment]
Hmmm... I maybe saw something about DNS provider social engineering on twitter... so case solved right?!
I'm sure Reddit will claim to. 
Main point is that sites get hacked, and multiple easy to verify sources should probably have the address listed in advance. Long term, I think ENS adoption is the best hope.

**Comment by maurelian** [comment]
I believe this is out of scope.
